[workspace]
resolver = "2"
members = [
    "service",
    "library",
]

[profile.release]
debug = true

[workspace.dependencies]
prometheus = "0.14"
r2d2 = "0.8"
r2d2_sqlite = "0.35"
rusqlite = { version = "0.40", features = ["bundled"] }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
