from glob import glob

print("//! Metadata files")
print("//!")
print("//! DO NOT EDIT MANUALLY")
print("//! generated by: python3 generate-meta-db.py > library/src/meta.rs")


def generate_version(version):
    folder = "./polyfill-libraries/" + version
    files = glob(folder + "/*/meta.json")
    safe_version = version.replace(".", "_")

    def key(name):
        return f"F_{safe_version}_" + name \
            .replace("/", "_") \
            .replace(".", "_") \
            .replace("-", "_") \
            .replace("~", "_") \
            .replace("@", "_") \
            .upper()

    for file in files:
        f = open(file, "r")
        contents = f.read()
        f.close()

        name = key(file.replace(folder, ""))

        contents = contents.replace("#", "\\\\#")

        print("const %s: &str = r#\"%s\"#;" % (name, contents))

    print("")
    print("pub(crate) fn lookup_" + safe_version + "(n: &str) -> Option<&'static str> {")
    print("  match n {")

    for file in files:
        name = file.replace(folder, "")
        print("    \"%s\" => Some(%s)," % (name, key(name)))

    print("    _ => None,")
    print("  }")
    print("}")


generate_version("3.101.0")
generate_version("3.103.0")
generate_version("3.104.0")
generate_version("3.108.0")
generate_version("3.109.0")
generate_version("3.110.1")
generate_version("3.111.0")
generate_version("3.27.4")
generate_version("3.34.0")
generate_version("3.39.0")
generate_version("3.40.0")
generate_version("3.41.0")
generate_version("3.42.0")
generate_version("3.46.0")
generate_version("3.48.0")
generate_version("3.50.2")
generate_version("3.51.0")
generate_version("3.52.0")
generate_version("3.52.1")
generate_version("3.52.2")
generate_version("3.52.3")
generate_version("3.53.1")
generate_version("3.89.4")
generate_version("3.96.0")
generate_version("3.98.0")
generate_version("4.8.0")
generate_version("3.25.1")
generate_version("5.3.1")
